### PR TITLE
Kill all the children, not just the firstborn

### LINKED ISSUE #159: Throwing on uncaughtException in spawnServer will leave orphaned processes around
When there's a test assertion failure that causes an uncaught exception, the first child process started by testium will shut down, and the [throw statement here](https://github.com/groupon/testium/blob/624f6a9ead734477948c92f1c82dcf1ea5929d4e/src/processes/server.coffee#L174) will go unhandled, killing mocha and leaving orphaned processes around.

In my case, `phantomjs` would shut down, but the proxy app & webapp will stay around.

Coffeescript code used to reproduce the issue:
```coffee
'use strict'

assert = require 'assertive'
injectBrowser = require 'testium/mocha'

describe 'Test', ->
  before injectBrowser()

  it 'when running an async test', (done) ->
    setTimeout (->
      assert.equal 0, 1
      done()
    ), 1000
```

Output:
```bash
$ make test-integration
1..1
not ok 1 Test when running an async test
  Error: Expected: 0
  Actually: 1
    at [object Object]._onTimeout (test/integration/heartbeat.test.coffee:11:14, <js>:11:16)


/Users/chkhoo/blah/node_modules/testium/lib/processes/server.js:192
      throw error;
            ^
Error: Expected: 0
Actually: 1
  at [object Object]._onTimeout (test/integration/heartbeat.test.coffee:11:14, <js>:11:16)

make: *** [test-integration] Error 1

$ ps aux | grep node
chkhoo           3843   0.0  0.2  3075476  15120 s002  S    11:55AM   0:00.08 node /Users/chkhoo/blah/node_modules/.bin/phantomjs --webdriver=57793 --webdriver-loglevel=DEBUG --ssl-protocol=tlsv1
chkhoo           3861   0.0  0.0  2432772    668 s002  S+   11:55AM   0:00.00 grep node
chkhoo           3855   0.0  1.7  3180196 144964 s002  S    11:55AM   0:04.09 /Users/chkhoo/.nvm/v0.10.37/bin/node /Users/chkhoo/blah/worker-shim.js
chkhoo           3854   0.0  1.6  3174052 136856 s002  S    11:55AM   0:04.05 /Users/chkhoo/.nvm/v0.10.37/bin/node /Users/chkhoo/blah/worker-shim.js
chkhoo           3845   0.0  0.7   857056  54660 s002  S    11:55AM   0:00.68 /Users/chkhoo/blah/node_modules/phantomjs/lib/phantom/bin/phantomjs --webdriver=57793 --webdriver-loglevel=DEBUG --ssl-protocol=tlsv1
chkhoo           3844   0.0  1.7  3176052 140320 s002  S    11:55AM   0:03.74 node ./node_modules/.bin/coffee core/master.coffee
s
```

When I comment out the throw line, this is what I get.

``` bash
$ make test-integration
1..1
not ok 1 Test when running an async test
  Error: Expected: 0
  Actually: 1
    at [object Object]._onTimeout (test/integration/heartbeat.test.coffee:11:14, <js>:11:16)

Error grabbing screenshot: Failure when receiving data from the peer
not ok 2  "after all" hook: closeBrowser
  Error: Couldn't connect to server (while closing browser)

# tests 2
# pass 0
# fail 2
make: *** [test-integration] Error 1
```

The good thing now is there's no orphaned processes, but the above error message might be another issue?  Or it's just that grabbing screenshot is being run multiple times and that causes a problem, etc.?

### PR DESCRIPTION
**Pull request by khoomeister**
process... that is.

Fixes #159

### CODE REVIEW

File: src/processes/server.coffee [hunk 1]
```diff
@@ -168,9 +171,10 @@ spawnServer = (logs, name, cmd, args, opts, cb) ->
         console.error err.stack
 
     process.on 'uncaughtException', (error) ->
-      try child.kill()
-      catch err
-        console.error err.stack
+      for childProcess in children
+        try childProcess.kill()
+        catch err
```
Comment (EndangeredMassa) [inline src/processes/server.coffee]: glad that `err` is different from `error`, but can we call this `childError` (or something like that) instead to be a little more clear?

Comment (khoomeister) [inline src/processes/server.coffee]: Sounds good - fixed.

**Comment by johan** [comment]
:heart: :+1: :joy:

**Comment by khoomeister** [comment]
Hey @EndangeredMassa, I've renamed the child error from `err` to `childErr`.

File: src/processes/server.coffee [hunk 2]
```diff
@@ -168,9 +171,10 @@ spawnServer = (logs, name, cmd, args, opts, cb) ->
...
 
     process.on 'uncaughtException', (error) ->
-      try child.kill()
-      catch err
-        console.error err.stack
+      for childProcess in children
+        try childProcess.kill()
+        catch childErr
+          console.error childErr.stack
       throw error
```
Comment (EndangeredMassa) [inline src/processes/server.coffee]: This will add a new `process.on 'uncaughtException'` handler for each child. We probably only need one.

Also, we should add something to each `child.on 'exit'` that calls this `killAllChildren` logic as well.

Comment (khoomeister) [inline src/processes/server.coffee]: Wouldn't `process.on 'uncaughtException'` just add a handler on the testium runner process?  We're trying to kill phantom, proxy & webapp at the same time before exiting gracefully.

Comment (EndangeredMassa) [inline src/processes/server.coffee]: It does, but if a child crashes, it doesn't kill the parent process because we already add an error handler on the child. That handler does not kill other children or the parent process, right now.

Comment (khoomeister) [inline src/processes/server.coffee]: Ahh OK, sounds good - will update accordingly.

Comment (khoomeister) [inline src/processes/server.coffee]: OK, it's updated.  What do you think?

**Comment by khoomeister** [comment]
I updated the code to include a "limit to one instance" check so the `process` object won't be filled up with more of the same listeners.

I also updated coffeescript to 1.9.3 to avoid this error when running `coffee -wcbo lib src`:

```
Error: The two following source files have the same output file:
    .../testium/src/processes/server.coffee
    .../testium/src/processes/server.coffee
```
Source: https://github.com/jashkenas/coffeescript/issues/3863

**Comment by khoomeister** [comment]
OK tests added - actually discovered that what what we wanted was the `exit` event in the child process, not `error`.

So if any child process exits with a non-zero code, it'll kill everything.

Exit event doco: https://nodejs.org/api/child_process.html#child_process_event_exit

I read through the [error event doco](https://nodejs.org/api/child_process.html#child_process_event_error), but I'm not exactly sure how it can be triggered.  Perhaps you'd know more, @EndangeredMassa?

But aside from that, what do you think of the approach?

**Comment by jkrems** [comment]
One example is [`ENOENT`](https://github.com/groupon/testium/blob/ck-kill-all-the-children/src/processes/server.coffee#L179). So passing a non-existent file as the command might do the trick.

**Comment by khoomeister** [comment]
OK, `ENOENT` will only occur only if the `node`, `coffee` or `phantomjs` executables aren't available in the PATH... so I killed the PATH env variable :see_no_evil: in the test.

OK, how's it looking now?

File: test/cleanup.test.coffee [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+rimraf = require 'rimraf'
+{extend} = require 'lodash'
+
+LOG_DIRECTORY = "#{__dirname}/cleanup_log"
+ENV_OVERRIDES = 
+  testium_logDirectory: LOG_DIRECTORY
+
+getNumProcesses = (done) ->
+  exec 'ps', (err, stdout, stderr) ->
+    numProcesses = stdout.split('\n').length - 1 # header line
```
Comment (EndangeredMassa) [inline test/cleanup.test.coffee]: Can we break on error here?

```coffeescript
return done(err) if err?
```

File: test/cleanup.test.coffee [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+assert = require 'assertive'
+rimraf = require 'rimraf'
+{extend} = require 'lodash'
+
+LOG_DIRECTORY = "#{__dirname}/cleanup_log"
+ENV_OVERRIDES = 
+  testium_logDirectory: LOG_DIRECTORY
+
+getNumProcesses = (done) ->
+  exec 'ps', (err, stdout, stderr) ->
```
Comment (EndangeredMassa) [inline test/cleanup.test.coffee]: I was afraid that this might make the test too flakey, but `ps` with no options actually sounds fine, I think.

> By default, ps selects all processes with the same effective user ID (euid=EUID) as the current user and associated with the same terminal as the invoker.

File: test/cleanup.test.coffee [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+    numProcesses = stdout.split('\n').length - 1 # header line
+    done numProcesses
+
+testFile = ({file, envOverrides, exitCode, done}) ->
+  envOverrides ?= {testium_app: null}
+  getNumProcesses (numProcessesBefore) ->
+
+    mocha = execFile './node_modules/.bin/mocha', [ file ], {
+      env: extend(envOverrides, ENV_OVERRIDES, process.env)
+    }, (err, stdout, stderr) ->
```
Comment (EndangeredMassa) [inline test/cleanup.test.coffee]: can we break on this `err` as well?

File: test/cleanup.test.coffee [hunk 6]
```diff
@@ -0,0 +1,76 @@
+{exec, execFile} = require 'child_process'
+
+assert = require 'assertive'
+rimraf = require 'rimraf'
+{extend} = require 'lodash'
+
+LOG_DIRECTORY = "#{__dirname}/cleanup_log"
+ENV_OVERRIDES =
```
Comment (EndangeredMassa) [inline test/cleanup.test.coffee]: Please remove extra whitespace at the end of this line.

File: test/cleanup_dead_child_app.coffee [hunk 7]
```diff
@@ -0,0 +1,10 @@
+http = require 'http'
+
+setTimeout ->
+  throw 'error!'
+, 2000
```
Comment (EndangeredMassa) [inline test/cleanup_dead_child_app.coffee]: Do we need to wait this long? This time adds directly to the suite run time. This test has the same result if we kill it immediately.

File: test/cleanup_exception_test.test.coffee [hunk 8]
```diff
@@ -0,0 +1,13 @@
...
+injectBrowser = require '../mocha'
+
+describe 'Failing test', ->
+  before injectBrowser()
+
+  it 'when running an async test', (done) ->
+    setTimeout ->
+      assert.equal 0, 1
+      done()
+    , 1000
```
Comment (EndangeredMassa) [inline test/cleanup_exception_test.test.coffee]: Do we need to wait this long?

**Comment by khoomeister** [comment]
Hey @EndangeredMassa, thanks for the feedback - I've made all the changes :smiley:

**Comment by EndangeredMassa** [comment]
published in [3.1.0](https://github.com/groupon/testium/releases/tag/v3.1.0)
